name: compras
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    provider: ^6.0.5
    intl: ^0.18.1

dev_dependencies:
    hive_generator: ^1.1.3
    build_runner: ^2.4.4

flutter:
    uses-material-design: true
